baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Connor Young'
theme = 'PaperMod'

[params]
env = 'production'
title = 'Connor Young'
description = 'Personal website of Connor Young'

	[params.profileMode]
	enabled = true # needs to be explicitly set
	title = "Welcome there folks! \U0001F44B"
	subtitle = "Full-stack engineer. Startup founder."

	[[params.socialIcons]]
	name = "linkedin"
	url = "https://www.linkedin.com/in/connor-young1/"

	[[params.socialIcons]]
	name = "github"
	url = "https://github.com/connoryoung7"
 
